name: SharApp
options:
  bundleIdPrefix: com.sharapp.ios
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

targets:
  SharApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: SharApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sharapp.ios.demo
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        UIMainStoryboardFile: ""
        INFOPLIST_FILE: SharApp/Application/Info.plist
    info:
      path: SharApp/Application/Info.plist
      properties:
        CFBundleName: SharApp
        CFBundleDisplayName: SharApp
        CFBundleIdentifier: com.sharapp.ios.demo
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIAppFonts:
          - PlusJakartaSans-Regular.ttf
          - PlusJakartaSans-Medium.ttf
          - PlusJakartaSans-SemiBold.ttf
          - PlusJakartaSans-Bold.ttf
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIStatusBarStyle: UIStatusBarStyleDarkContent
    resources:
      - path: SharApp/Resources

  SharAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SharAppTests
    dependencies:
      - target: SharApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sharapp.ios.demo.tests
